# Generated by Django 3.2.18 on 2023-03-11 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(max_length=50)),
                ('age', models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.school',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(max_length=50)),
                ('age', models.PositiveBigIntegerField(default=18)),
                (
                    'school',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.school',
                    ),
                ),
                (
                    'students',
                    models.ManyToManyField(
                        blank=True, related_name='teachers', to='app.Student'
                    ),
                ),
                (
                    'subjects',
                    models.ManyToManyField(
                        blank=True, related_name='teachers', to='app.Subject'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(
                blank=True, related_name='students', to='app.Subject'
            ),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.teacher',
                    ),
                ),
                (
                    'for_student',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.student',
                    ),
                ),
                (
                    'for_subject',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.subject',
                    ),
                ),
            ],
        ),
    ]
